name: "Check Documentation"
on:
  push:
    paths:
      - ".github/workflows/docs-check.yml"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/docs-check.yml"
      - "src/**"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: npm install -g @devcontainers/cli
        name: Install devcontainer CLI

      - name: Check for documentation updates
        run: |
          (cd ./src && devcontainer features generate-docs -n "NicoVIII/devcontainer-features")
          if [ -z "$(git status --porcelain=v1)" ]; then
            echo "Documentation is up to date."
          else
            echo "Documentation may need to be updated. Please run '(cd ./src && devcontainer features generate-docs -n \"NicoVIII/devcontainer-features\")' and commit the changes."
            exit 1
          fi
